# action.yml
name: "Verify NPM files action"
description: "Verifies files are present and matched in dist."
inputs:
  files:
    description: |
      New line deliminated list of files to verify.
    required: false
    default: |
      main      
runs:
  using: 'node12'
  main: 'dist/index.js'
